library(dplyr)
Sys.setlocale("LC_TIME", "C")
data <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
datarequired <- filter(data, Date=="1/2/2007" | Date=="2/2/2007")
datarequired[,1] <- as.Date(datarequired[,1], "%d/%m/%Y")
datarequired$numformat <- as.POSIXct(paste(datarequired[,1], datarequired[,2]))
png("plot2.png", width=480, height=480, bg="white")
plot(datarequired$numformat, as.numeric(datarequired[,3]), type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()