library(dplyr)
Sys.setlocale("LC_TIME", "C")
data <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
datarequired <- filter(data, Date=="1/2/2007" | Date=="2/2/2007")
datarequired[,1] <- as.Date(datarequired[,1], "%d/%m/%Y")
datarequired$numformat <- as.POSIXct(paste(datarequired[,1], datarequired[,2]))
png("plot3.png", width=480, height=480, bg="white")
plot(datarequired[,10],datarequired[,7], type="l", xlab="", ylab="Energy sub metering", col="black")
lines(datarequired[,10],datarequired[,8], col="red")
lines(datarequired[,10],datarequired[,9], col="blue")
legend("topright", lty=1, legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),  col=c("black","red","blue"))
dev.off()